- name: Import Visual Studio Code key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code YUM repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

# https://fedoraproject.org/wiki/Workstation/Third_Party_Software_Repositories#Managing_third_party_repositories_using_DNF
- name: Install Fedora Work Stations
  package:
      name: fedora-workstation-repositories
      state: present

# https://docs.fedoraproject.org/en-US/quick-docs/installing-chromium-or-google-chrome-browsers/
- name: Enable Google Chrome in fedora-workstation-repositories
  command: dnf config-manager --set-enabled google-chrome

- name: Install applications.
  package:
      name: "{{ item }}"
      state: present
      update_cache: yes
  loop:
    - flatpak
    - ansible
    - tigervnc
    - keepassxc
    - bleachbit
    # Dev
    - jq
    - vim
    - gvim
    - code
    # Multimedia
    - vlc
    - clementine
    # Archivers
    - p7zip
    - p7zip-plugins
    - unrar
    # Gaming
    - lutris
    - steam
    - playonlinux
    # Internet stuff
    - qbittorrent
    - quassel
    - thunderbird
    - weechat
    - firefox
    - google-chrome-stable
    # Disable mouse accel
    - xset
    # Pretty print sys info
    - neofetch
    - inxi
    # GUI menu editor
    - menulibre
    # Screenshots
    - shutter
    # Terminal file manager
    - mc
    # PDF reader
    - okular
    # Simple scanning
    - simple-scan
    # Mail
    - mailx
    - postfix
    # Sys monitoring
    - htop
    - iotop
    - lm_sensors
    - xsensors
    - logwatch
    # Benchmarking & stress tests
    - phoronix-test-suite
    - stress-ng
    - corectrl
    # SELinux
    - setroubleshoot
    - setroubleshoot-plugins
    # display management
    - autorandr
    # graphics
    - pinta

- name: Install group packages.
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "@Development tools"
    - "@Multimedia"
    - "@Sound-and-video"
    - "@i3-desktop-environment"
    - "@virtualization"

- name: Enable Flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install AMD tools.
  package:
      name: "{{ item }}"
      state: present
  loop:
    - radeontop
  when: using_amd_gpu

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
