---
- name: Create user .xprofile file
  file:
    path: "/home/{{ username }}/.xprofile"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    state: touch

- name: Adding customisations to the /home/$USER/.xprofile file
  template: # https://docs.ansible.com/ansible/latest/modules/template_module.html
    src: templates/vimrc-both.j2
    dest: "/home/{{ username }}/.xprofile"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

